USE SHOPOFQA;
GO
-----------------PROCEDURE----------------------------
--BẢNG TÀI KHOẢN
--Đăng ký
ALTER PROC [dbo].[ST_signIn](@USER VARCHAR(30),@PASS VARCHAR(16),@TYPE VARCHAR(5))
AS
BEGIN
IF(@TYPE='1')
BEGIN
SELECT DBO.ACCOUNT.ACCOUNTID,DBO.ACCOUNT.ACCOUNTNAME,DBO.ACCOUNT.ACCOUNTWALLET FROM DBO.ACCOUNT 
WHERE DBO.ACCOUNT.ACCOUNTNUMBERPHONE=@USER AND DBO.ACCOUNT.ACCOUNTPASSWORD=@PASS
END
IF(@TYPE='2')
BEGIN
SELECT DBO.ACCOUNT.ACCOUNTID,DBO.ACCOUNT.ACCOUNTNAME,DBO.ACCOUNT.ACCOUNTWALLET FROM DBO.ACCOUNT 
WHERE DBO.ACCOUNT.ACCOUNTEMAIL=@USER AND DBO.ACCOUNT.ACCOUNTPASSWORD=@PASS
END
IF(@TYPE='0')
BEGIN
SELECT DBO.ACCOUNT.ACCOUNTID,DBO.ACCOUNT.ACCOUNTNAME,DBO.ACCOUNT.ACCOUNTWALLET FROM DBO.ACCOUNT 
WHERE DBO.ACCOUNT.ACCOUNTUSERNAME=@USER AND DBO.ACCOUNT.ACCOUNTPASSWORD=@PASS
END
END

GO
ALTER PROC ST_ACCOUNT
(
    @ACCOUNTEMAIL VARCHAR(30),
    @ACCOUNTUSERNAME VARCHAR(30),
    @ACCOUNTNUMBERPHONE VARCHAR(15),
    @ACCOUNTPASSWORD VARCHAR(16)
)
AS
BEGIN
    IF (
           @ACCOUNTNUMBERPHONE IS NULL
           AND @ACCOUNTUSERNAME IS NULL
           AND @ACCOUNTEMAIL IS NULL
       )
    BEGIN
        RETURN;
    END;
    IF (@ACCOUNTPASSWORD IS NULL)
        RETURN;
    IF (@ACCOUNTEMAIL IN
        (
            SELECT DBO.ACCOUNT.ACCOUNTEMAIL
            FROM DBO.ACCOUNT
            WHERE ACCOUNTEMAIL IS NOT NULL
        )
       )
        RETURN;
    IF (@ACCOUNTUSERNAME IN
        (
            SELECT DBO.ACCOUNT.ACCOUNTUSERNAME
            FROM DBO.ACCOUNT
            WHERE ACCOUNTUSERNAME IS NOT NULL
        )
       )
        RETURN;
    IF (@ACCOUNTNUMBERPHONE IN
        (
            SELECT DBO.ACCOUNT.ACCOUNTNUMBERPHONE
            FROM DBO.ACCOUNT
            WHERE ACCOUNTNUMBERPHONE IS NOT NULL
        )
       )
        RETURN;
    INSERT INTO DBO.ACCOUNT
    (
        ACCOUNTEMAIL,
        ACCOUNTUSERNAME,
        ACCOUNTNUMBERPHONE,
        ACCOUNTPASSWORD,
        ACCOUNTSTATUSID,
        ACCOUNTSEXID
    )
    VALUES
    (@ACCOUNTEMAIL, @ACCOUNTUSERNAME, @ACCOUNTNUMBERPHONE, @ACCOUNTPASSWORD, 'C506315C-FC60-4CC7-87E3-DDDA16F8780A',
     'E68C67E6-CA3E-4208-B23D-FF6092E56ACC');
END;
--CẬP NHẬT TÀI KHOẢN
GO
CREATE PROC UPDATE_ACCOUNT
(
    @ACCOUNTID UNIQUEIDENTIFIER,
    @ACCOUNTSEXCODE VARCHAR(15),
    @ACCOUNTNAME NVARCHAR(50),
    @ACCOUNTBORN DATE,
    @ACCOUNTADDRESS NVARCHAR(50),
    @ACCOUNTDETAILADDRESS NVARCHAR(MAX),
    @ACCOUNTPHONENUMBER VARCHAR(15)
)
AS
BEGIN
    IF (
           @ACCOUNTSEXCODE IS NULL
           OR @ACCOUNTNAME IS NULL
           OR @ACCOUNTBORN IS NULL
           OR @ACCOUNTADDRESS IS NULL
           OR @ACCOUNTDETAILADDRESS IS NULL
           OR @ACCOUNTPHONENUMBER IS NULL
       )
        RETURN;
    UPDATE DBO.ACCOUNT
    SET ACCOUNTSEXID =
        (
            SELECT DBO.SEX.SEXID FROM DBO.SEX WHERE DBO.SEX.SEXCODE = @ACCOUNTSEXCODE
        ),
        ACCOUNTNAME = @ACCOUNTNAME,
        ACCOUNTBORN = @ACCOUNTBORN,
        ACCOUNTADDRESS = @ACCOUNTADDRESS,
        ACCOUNTDETAILADDRESS = @ACCOUNTDETAILADDRESS,
        ACCOUNTPHONENUMBER = @ACCOUNTPHONENUMBER
    WHERE ACCOUNTID = @ACCOUNTID;
END;
--ĐỔI MẬT KHẨU
GO
CREATE PROC UPDATE_ACOUNT_PASSWORD(@ACCOUNTID UNIQUEIDENTIFIER,@NEWPASSWORD VARCHAR(16))
AS
BEGIN
UPDATE dbo.ACCOUNT
SET ACCOUNTPASSWORD =@NEWPASSWORD
WHERE ACCOUNTID = @ACCOUNTID
END
-----------------FUNCTION-----------------------------
GO
CREATE FUNCTION GET_ACCOUNTID_EMAIL
(
    @ACCOUNTEMAIL VARCHAR(30)
)
RETURNS UNIQUEIDENTIFIER
AS
BEGIN
    RETURN
    (
        SELECT DBO.ACCOUNT.ACCOUNTID
        FROM DBO.ACCOUNT
        WHERE ACCOUNTEMAIL = @ACCOUNTEMAIL
    );
END;
GO
ALTER FUNCTION GET_ACCOUNTID_USERNAME
(
    @ACCOUNTUSERNAME VARCHAR(30)
)
RETURNS UNIQUEIDENTIFIER
AS
BEGIN
    RETURN
    (
        SELECT DBO.ACCOUNT.ACCOUNTID
        FROM DBO.ACCOUNT
        WHERE ACCOUNTUSERNAME = @ACCOUNTUSERNAME
    );
END;
GO
ALTER FUNCTION GET_ACCOUNTID_PHONENUMBER
(
    @ACCOUNTNUMBERPHONE VARCHAR(30)
)
RETURNS UNIQUEIDENTIFIER
AS
BEGIN
    RETURN
    (
        SELECT DBO.ACCOUNT.ACCOUNTID
        FROM DBO.ACCOUNT
        WHERE ACCOUNTNUMBERPHONE = @ACCOUNTNUMBERPHONE
    );
END;
-----------------TESTER INSERT------------------------
GO

SELECT * FROM dbo.ACCOUNT