/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Form;

import java.awt.Image;
import javax.swing.ImageIcon;
import Services.Img;
import java.awt.Color;
import java.awt.Container;
import java.awt.FlowLayout;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author PC
 */
public class SignUpFormSetUpInfo extends javax.swing.JFrame {

    // This is variable Form do not delete or update if you guys do not understand applacation stream
    private MainForm _mainForm;
    private SignInForm _signInForn;
    
    public static void main(String[] args) {
        SignUpFormSetUpInfo s = new SignUpFormSetUpInfo("","");
        s.setVisible(true);
    }

    // This is variable Form do not delete or update if you guys do not understand applacation stream
    public SignUpFormSetUpInfo(String accountSdt,String accountPass) {
        initComponents();
        setLogoAndContent();
        addMonthYear();
        addDay(1950, 1);
        Container con = this.getContentPane();
        con.setBackground(Color.WHITE);
        setLocationRelativeTo(this);
    }
    
    private void addMonthYear() {
        DefaultComboBoxModel dcmYear = (DefaultComboBoxModel) cbbYear.getModel();
        dcmYear.removeAllElements();
        for (int i = 1950; i < 2020; i++) {
            dcmYear.addElement(String.valueOf(i));
        }
        cbbYear.setModel(dcmYear);
        DefaultComboBoxModel dcmMonth = (DefaultComboBoxModel) cbbMonth.getModel();
        dcmMonth.removeAllElements();
        for (int i = 1; i < 13; i++) {
            dcmMonth.addElement(String.valueOf(i));
        }
        cbbMonth.setModel(dcmMonth);
    }
    
    private void addDay(int year, int month) {
        int i = 0;
        if (year % 4 == 0) {
            if (month == 2) {
                i = 29;
                addDay(i);
                return;
            }
        } else {
            if (month == 2) {
                i = 28;
                addDay(i);
                return;
            }
        }
        if (month == 4 || month == 6 || month == 9 || month == 11) {
            i = 30;
            addDay(i);
            return;
        } else {
            i = 31;
            addDay(i);
            return;
        }
    }
    
    private void addDay(int i) {
        DefaultComboBoxModel dcmDay = (DefaultComboBoxModel) cbbDay.getModel();
        dcmDay.removeAllElements();
        for (int j = 1; j <= i; j++) {
            dcmDay.addElement(String.valueOf("Ngày " + j));
        }
        cbbDay.setModel(dcmDay);
    }
    
    private void setLogoAndContent() {
        ImageIcon imgLogo = new ImageIcon("C:\\Users\\PC\\Desktop\\jav3\\icon-jav3-signin\\logoshop.png");
        ImageIcon content = new ImageIcon("C:\\Users\\PC\\Desktop\\jav3\\icon-jav3-signin\\content.png");
        ImageIcon footer = new ImageIcon("C:\\Users\\PC\\Desktop\\jav3\\icon-jav3-signin\\footer.png");
        jlabelLogo.setIcon(new ImageIcon(Img.resizer(imgLogo.getImage(), 129, 100)));
        jlabelFooter.setIcon(new ImageIcon(Img.resizer(footer.getImage(), 1376, 245)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jlabelLogo = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtAccountName = new javax.swing.JTextField();
        btnConfỉm = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jlabelSignIn = new javax.swing.JLabel();
        txtAccountAddress = new javax.swing.JTextField();
        txtAccountPhoneNumber = new javax.swing.JTextField();
        rdoAccountSexOptMen = new javax.swing.JRadioButton();
        rdoAccountSexOptWoman = new javax.swing.JRadioButton();
        cbbDay = new javax.swing.JComboBox<>();
        cbbMonth = new javax.swing.JComboBox<>();
        cbbYear = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cbAgreeShopRules = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        jlabelFooter = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Shoppee");
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximizedBounds(new java.awt.Rectangle(1376, 979, 979, 979));
        setMinimumSize(new java.awt.Dimension(1376, 979));
        setResizable(false);
        setSize(new java.awt.Dimension(1376, 979));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 87, 35));
        jLabel1.setText("Bạn cần giúp đỡ?");

        jlabelLogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlabelLogoMouseClicked(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Đăng ký");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(191, 191, 191)
                .addComponent(jlabelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 646, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jlabelLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 21, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(241, 76, 50));
        jPanel2.setMaximumSize(new java.awt.Dimension(1376, 600));
        jPanel2.setMinimumSize(new java.awt.Dimension(1376, 600));
        jPanel2.setPreferredSize(new java.awt.Dimension(1376, 600));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Xin chào! cho mình xin ít phút trước khi bắt đầu mua sắm nhé =.=");

        txtAccountName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtAccountName.setForeground(new java.awt.Color(204, 204, 204));
        txtAccountName.setText("Họ tên bạn nè..");
        txtAccountName.setMargin(new java.awt.Insets(2, 10, 2, 2));
        txtAccountName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtAccountNameMouseClicked(evt);
            }
        });

        btnConfỉm.setBackground(new java.awt.Color(241, 76, 50));
        btnConfỉm.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnConfỉm.setForeground(new java.awt.Color(255, 255, 255));
        btnConfỉm.setText("Xác Nhận");
        btnConfỉm.setBorder(null);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 153, 153));
        jLabel8.setText("Bạn đã có tài khoản?");

        jlabelSignIn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlabelSignIn.setForeground(new java.awt.Color(241, 76, 50));
        jlabelSignIn.setText("Đăng nhập");
        jlabelSignIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlabelSignInMouseClicked(evt);
            }
        });

        txtAccountAddress.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtAccountAddress.setForeground(new java.awt.Color(204, 204, 204));
        txtAccountAddress.setText("Địa chỉ của bạn..");
        txtAccountAddress.setMargin(new java.awt.Insets(2, 10, 2, 2));
        txtAccountAddress.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtAccountAddressMouseClicked(evt);
            }
        });

        txtAccountPhoneNumber.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtAccountPhoneNumber.setForeground(new java.awt.Color(204, 204, 204));
        txtAccountPhoneNumber.setText("Số điện thoại nè..");
        txtAccountPhoneNumber.setMargin(new java.awt.Insets(2, 10, 2, 2));
        txtAccountPhoneNumber.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtAccountPhoneNumberMouseClicked(evt);
            }
        });

        rdoAccountSexOptMen.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rdoAccountSexOptMen);
        rdoAccountSexOptMen.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rdoAccountSexOptMen.setSelected(true);
        rdoAccountSexOptMen.setText("Nam");

        rdoAccountSexOptWoman.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rdoAccountSexOptWoman);
        rdoAccountSexOptWoman.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rdoAccountSexOptWoman.setText("Nữ");

        cbbMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbMonthActionPerformed(evt);
            }
        });

        cbbYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbYearActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Ngày tháng năm sinh bạn..");

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setForeground(new java.awt.Color(241, 76, 50));
        jLabel5.setText("Chính sách về bảo mật ");

        jLabel6.setForeground(new java.awt.Color(241, 76, 50));
        jLabel6.setText("Quyền lợi khách hàng.");

        jLabel7.setText("&&");

        cbAgreeShopRules.setBackground(new java.awt.Color(255, 255, 255));
        cbAgreeShopRules.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(cbAgreeShopRules)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cbAgreeShopRules, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGap(90, 90, 90)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jlabelSignIn))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                    .addGap(16, 16, 16)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btnConfỉm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtAccountName)
                                        .addComponent(txtAccountPhoneNumber)
                                        .addComponent(txtAccountAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                                    .addComponent(cbbDay, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(28, 28, 28)
                                                    .addComponent(cbbMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGap(29, 29, 29)
                                            .addComponent(cbbYear, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addComponent(rdoAccountSexOptMen, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(rdoAccountSexOptWoman, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(txtAccountName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtAccountPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbbDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(txtAccountAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdoAccountSexOptMen)
                    .addComponent(rdoAccountSexOptWoman))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnConfỉm, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(jlabelSignIn))
                .addGap(67, 67, 67))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(379, 379, 379)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(393, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jlabelFooter.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlabelFooter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlabelFooter, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAccountNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAccountNameMouseClicked
        txtAccountName.setText("");
        txtAccountName.setForeground(Color.BLACK);
    }//GEN-LAST:event_txtAccountNameMouseClicked

    private void jlabelLogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabelLogoMouseClicked
        _mainForm = new MainForm();
        this.dispose();
        _mainForm.setVisible(true);
    }//GEN-LAST:event_jlabelLogoMouseClicked

    private void jlabelSignInMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabelSignInMouseClicked
        _signInForn = new SignInForm();
        this.dispose();
        _signInForn.setVisible(true);
    }//GEN-LAST:event_jlabelSignInMouseClicked

    private void txtAccountAddressMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAccountAddressMouseClicked
        txtAccountAddress.setText("");
        txtAccountAddress.setForeground(Color.BLACK);
        
    }//GEN-LAST:event_txtAccountAddressMouseClicked

    private void txtAccountPhoneNumberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAccountPhoneNumberMouseClicked
        txtAccountPhoneNumber.setText("");
        txtAccountPhoneNumber.setForeground(Color.BLACK);
    }//GEN-LAST:event_txtAccountPhoneNumberMouseClicked

    private void cbbYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbYearActionPerformed
        int getYear = Integer.parseInt(cbbYear.getSelectedItem().toString());
        int getMonth = cbbMonth.getSelectedIndex() + 1;
        addDay(getYear, getMonth);
    }//GEN-LAST:event_cbbYearActionPerformed

    private void cbbMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbMonthActionPerformed
        int getYear = Integer.parseInt(cbbYear.getSelectedItem().toString());
        int getMonth = cbbMonth.getSelectedIndex() + 1;
        addDay(getYear, getMonth);
    }//GEN-LAST:event_cbbMonthActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfỉm;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox cbAgreeShopRules;
    private javax.swing.JComboBox<String> cbbDay;
    private javax.swing.JComboBox<String> cbbMonth;
    private javax.swing.JComboBox<String> cbbYear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel jlabelFooter;
    private javax.swing.JLabel jlabelLogo;
    private javax.swing.JLabel jlabelSignIn;
    private javax.swing.JRadioButton rdoAccountSexOptMen;
    private javax.swing.JRadioButton rdoAccountSexOptWoman;
    private javax.swing.JTextField txtAccountAddress;
    private javax.swing.JTextField txtAccountName;
    private javax.swing.JTextField txtAccountPhoneNumber;
    // End of variables declaration//GEN-END:variables
}
