USE SHOPOFQA;
GO
-----------------Procedure----------------------------
--Bảng tài khoản
GO
ALTER PROC ST_ACCOUNT
(
    @ACCOUNTEMAIL VARCHAR(30),
    @ACCOUNTUSERNAME VARCHAR(30),
    @ACCOUNTNUMBERPHONE VARCHAR(15),
    @ACCOUNTPASSWORD VARCHAR(16)
)
AS
BEGIN
    IF (
           @ACCOUNTNUMBERPHONE IS NULL
           AND @ACCOUNTUSERNAME IS NULL
           AND @ACCOUNTEMAIL IS NULL
       )
    BEGIN
        RETURN;
    END;
    IF (@ACCOUNTPASSWORD IS NULL)
        RETURN;
    IF (@ACCOUNTEMAIL IN
        (
            SELECT dbo.ACCOUNT.ACCOUNTEMAIL
            FROM dbo.ACCOUNT
            WHERE ACCOUNTEMAIL IS NOT NULL
        )
       )
        RETURN;
    IF (@ACCOUNTUSERNAME IN
        (
            SELECT dbo.ACCOUNT.ACCOUNTUSERNAME
            FROM dbo.ACCOUNT
            WHERE ACCOUNTUSERNAME IS NOT NULL
        )
       )
        RETURN;
    IF (@ACCOUNTNUMBERPHONE IN
        (
            SELECT dbo.ACCOUNT.ACCOUNTNUMBERPHONE
            FROM dbo.ACCOUNT
            WHERE ACCOUNTNUMBERPHONE IS NOT NULL
        )
       )
        RETURN;
    INSERT INTO dbo.ACCOUNT
    (
        ACCOUNTEMAIL,
        ACCOUNTUSERNAME,
        ACCOUNTNUMBERPHONE,
        ACCOUNTPASSWORD,
        ACCOUNTSTATUSID,
        ACCOUNTSEXID
    )
    VALUES
    (@ACCOUNTEMAIL, @ACCOUNTUSERNAME, @ACCOUNTNUMBERPHONE, @ACCOUNTPASSWORD, 'C506315C-FC60-4CC7-87E3-DDDA16F8780A',
     'E68C67E6-CA3E-4208-B23D-FF6092E56ACC');
END;
--cập nhật tài khoản
GO
CREATE PROC UPDATE_ACCOUNT
(
    @ACCOUNTID UNIQUEIDENTIFIER,
    @ACCOUNTSEXCODE VARCHAR(15),
    @ACCOUNTNAME NVARCHAR(50),
    @ACCOUNTBORN DATE,
    @ACCOUNTADDRESS NVARCHAR(50),
    @ACCOUNTDETAILADDRESS NVARCHAR(MAX),
    @ACCOUNTPHONENUMBER VARCHAR(15)
)
AS
BEGIN
    IF (
           @ACCOUNTSEXCODE IS NULL
           OR @ACCOUNTNAME IS NULL
           OR @ACCOUNTBORN IS NULL
           OR @ACCOUNTADDRESS IS NULL
           OR @ACCOUNTDETAILADDRESS IS NULL
           OR @ACCOUNTPHONENUMBER IS NULL
       )
        RETURN;
    UPDATE dbo.ACCOUNT
    SET ACCOUNTSEXID =
        (
            SELECT dbo.SEX.SEXID FROM dbo.SEX WHERE dbo.SEX.SEXCODE = @ACCOUNTSEXCODE
        ),
        ACCOUNTNAME = @ACCOUNTNAME,
        ACCOUNTBORN = @ACCOUNTBORN,
        ACCOUNTADDRESS = @ACCOUNTADDRESS,
        ACCOUNTDETAILADDRESS = @ACCOUNTDETAILADDRESS,
        ACCOUNTPHONENUMBER = @ACCOUNTPHONENUMBER
    WHERE ACCOUNTID = @ACCOUNTID;
END;
--đổi mật khẩu
GO
CREATE PROC UPDATE_acount_password(@ACCOUNTID UNIQUEIDENTIFIER,@ACCOUNTPASSWORD VARCHAR(16),@newPassword VARCHAR(16))
AS
BEGIN

END
-----------------Function-----------------------------
GO
CREATE FUNCTION get_accountid_email
(
    @ACCOUNTEMAIL VARCHAR(30)
)
RETURNS UNIQUEIDENTIFIER
AS
BEGIN
    RETURN
    (
        SELECT dbo.ACCOUNT.ACCOUNTID
        FROM dbo.ACCOUNT
        WHERE ACCOUNTEMAIL = @ACCOUNTEMAIL
    );
END;
GO
ALTER FUNCTION get_accountid_username
(
    @ACCOUNTUSERNAME VARCHAR(30)
)
RETURNS UNIQUEIDENTIFIER
AS
BEGIN
    RETURN
    (
        SELECT dbo.ACCOUNT.ACCOUNTID
        FROM dbo.ACCOUNT
        WHERE ACCOUNTUSERNAME = @ACCOUNTUSERNAME
    );
END;
GO
ALTER FUNCTION get_accountid_phonenumber
(
    @ACCOUNTNUMBERPHONE VARCHAR(30)
)
RETURNS UNIQUEIDENTIFIER
AS
BEGIN
    RETURN
    (
        SELECT dbo.ACCOUNT.ACCOUNTID
        FROM dbo.ACCOUNT
        WHERE ACCOUNTNUMBERPHONE = @ACCOUNTNUMBERPHONE
    );
END;
-----------------TESTER INSERT------------------------
GO
